/**
 * aiOperationsService.js
 * Phase 7B: AI Operations Layer
 * 
 * Defines deterministic AI boundaries for the workflow engine.
 */

const db = require('../db');

/**
 * Executes a specialized AI action as part of a workflow.
 * AI agents may draft actions, recommend, generate playbooks, and request approvals.
 * AI agents may NOT execute executive decisions.
 * 
 * @param {Object} execution - The workflow_executions record
 * @param {Object} task - The workflow_tasks record
 */
const executeAITask = async (execution, task) => {
  const agentName = task.assigned_to || 'Workflow Copilot';
  const actionType = task.title;
  let outputResult = { status: 'success', recommendations: [] };

  console.log(`[AI Operations] ${agentName} executing: ${actionType}`);

  // Mock AI intelligence generation based on the action requested
  if (actionType.includes('Draft')) {
    outputResult.draftText = `Automated draft generated by ${agentName} at ${new Date().toISOString()}`;
  } else if (actionType.includes('Analyze')) {
    outputResult.analysis = 'Risk factors identified. Executive intervention recommended.';
    outputResult.riskLevel = 'High';
  } else if (actionType.includes('Approval Request')) {
    outputResult.justification = 'SLA threshold exceeded. Requesting manager approval.';
  } else {
    outputResult.summary = 'Task analyzed and recommendations generated.';
  }

  // Audit Log Generation per Phase 7B requirements
  await db.query(
    `INSERT INTO public.ai_operations_log (execution_id, task_id, agent_name, action_type, input_context, output_result)
     VALUES ($1, $2, $3, $4, $5, $6)`,
    [execution.id, task.id, agentName, actionType, JSON.stringify(execution.context_data), JSON.stringify(outputResult)]
  );

  return outputResult;
};

/**
 * Helper to fetch AI audit traces for the frontend
 */
const getAITraces = async (limit = 50) => {
  const { rows } = await db.query(
    `SELECT * FROM public.ai_operations_log ORDER BY created_at DESC LIMIT $1`,
    [limit]
  );
  return rows;
};

const logAITrace = async (executionId, taskId, agentName, actionType, inputContext, outputResult) => {
  await db.query(
    `INSERT INTO public.ai_operations_log (execution_id, task_id, agent_name, action_type, input_context, output_result)
     VALUES ($1, $2, $3, $4, $5, $6)`,
    [executionId, taskId, agentName, actionType, JSON.stringify(inputContext), JSON.stringify(outputResult)]
  );
};

module.exports = {
  executeAITask,
  getAITraces,
  logAITrace
};
