BEGIN;

ALTER TABLE public.leads
ADD COLUMN IF NOT EXISTS proposal_generated BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS final_deal_value DECIMAL(12,2),
ADD COLUMN IF NOT EXISTS close_notes TEXT;

COMMIT;
